/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        foreground: '#020617',
        card: '#ffffff',
        'card-foreground': '#020617',
        primary: '#041627',
        'primary-foreground': '#ffffff',
        secondary: '#006397',
        'secondary-foreground': '#ffffff',
        accent: '#5cb8fd',
        'accent-foreground': '#00476e',
        destructive: '#ba1a1a',
        'destructive-foreground': '#ffffff',
        border: '#c4c6cd',
        input: '#ffffff',
        ring: '#006397',
        tertiary: '#0f171a',
        'on-background': '#0b1c30',
        'on-error': '#ffffff',
        'on-surface': '#0b1c30',
        'surface-container-low': '#eff4ff',
        outline: '#74777d',
        'primary-fixed': '#d2e4fb',
        'on-error-container': '#93000a',
        'surface-container': '#e5eeff',
        'on-surface-variant': '#44474c',
        error: '#ba1a1a',
        'inverse-surface': '#213145',
        'tertiary-fixed': '#dce3e8',
        'on-tertiary-fixed-variant': '#41484c',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed': '#0b1d2d',
        'surface-container-high': '#dce9ff',
        'inverse-primary': '#b7c8de',
        'surface-tint': '#4f6073',
        'on-secondary-fixed-variant': '#004b73',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#001d31',
        'primary-fixed-dim': '#b7c8de',
        'surface-variant': '#d3e4fe',
        'surface-dim': '#cbdbf5',
        'secondary-fixed-dim': '#92ccff',
        'tertiary-fixed-dim': '#c0c7cc',
        'secondary-container': '#5cb8fd',
        'primary-container': '#1a2b3c',
        'outline-variant': '#c4c6cd',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#38485a',
        'on-primary-container': '#8192a7',
        'on-secondary-container': '#00476e',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'tertiary-container': '#242b2f',
        'secondary-fixed': '#cce5ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#151d20',
        'on-tertiary-container': '#8b9297',
        'inverse-on-surface': '#eaf1ff',
        surface: '#f8f9ff',
      },
       spacing: {
        base: '4px',
        xs: '4px',
        lg: '24px',
        xl: '32px',
        md: '16px',
        'sidebar-width': '280px',
        'container-max': '1440px',
        sm: '8px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontSize: {
        'mono-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
